# Generated by Django 4.0.3 on 2022-04-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_alter_progressreport_student_and_subject'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.subject'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='task',
            field=models.TextField(),
        ),
    ]
