# Generated by Django 4.0.3 on 2022-04-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0008_alter_progressreport_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eighth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eighth_period', to='parent.subject')),
                ('fifth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_period', to='parent.subject')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_period', to='parent.subject')),
                ('fourth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_period', to='parent.subject')),
                ('ninth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninth_period', to='parent.subject')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_period', to='parent.subject')),
                ('seventh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seventh_period', to='parent.subject')),
                ('sixth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth_period', to='parent.subject')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_period', to='parent.subject')),
            ],
        ),
    ]
