# Generated by Django 4.0.3 on 2022-04-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eighth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eighth_period', to='child.subject')),
                ('fifth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_period', to='child.subject')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_period', to='child.subject')),
                ('fourth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_period', to='child.subject')),
                ('grade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='child.grade')),
                ('ninth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninth_period', to='child.subject')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_period', to='child.subject')),
                ('seventh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seventh_period', to='child.subject')),
                ('sixth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth_period', to='child.subject')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_period', to='child.subject')),
            ],
        ),
    ]
