# Generated by Django 4.0.3 on 2022-04-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='day',
            field=models.CharField(default='Sunday', max_length=10),
        ),
    ]
