# Generated by Django 4.0.3 on 2022-03-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgressReport',
            new_name='Progress',
        ),
    ]
