# Generated by Django 4.0.3 on 2022-03-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_rename_progressreport_progress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progress',
            new_name='Progress1',
        ),
    ]
