# Generated by Django 4.0.3 on 2022-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_rename_progress_progress1'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress1',
            name='x',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
