# Generated by Django 4.0.3 on 2022-03-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_progress1_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('student_and_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.childsubject')),
            ],
        ),
        migrations.DeleteModel(
            name='Progress1',
        ),
    ]
