# Generated by Django 4.0.3 on 2022-04-02 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0007_alter_child_current_class_alter_progressreport_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='marks',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
