# Generated by Django 4.0.3 on 2022-03-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testauth',
            options={'ordering': ['title']},
        ),
    ]
