# Generated by Django 4.0.3 on 2022-03-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_testauth_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAuth',
        ),
    ]
