# Generated by Django 4.0.3 on 2022-04-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_alter_progressreport_student_and_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.CharField(default='', max_length=200),
        ),
    ]
