# Generated by Django 4.0.3 on 2022-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_child_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='imageUrl',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png'),
        ),
    ]
